USE ClothingStore
GO

-- TRANSACTION 1


ALTER DATABASE ClothingStore
SET ALLOW_SNAPSHOT_ISOLATION ON

SET TRANSACTION ISOLATION LEVEL SNAPSHOT

BEGIN TRAN
	SELECT *
	FROM Collection
	WHERE Did LIKE 'BB'

	UPDATE Collection
	SET Year=2022
	WHERE Did LIKE 'BB'
COMMIT TRAN

UPDATE Collection
SET Year=2020
WHERE Did LIKE 'BB'

ALTER DATABASE ClothingStore
SET ALLOW_SNAPSHOT_ISOLATION OFF